server:
  port: 8101
#  context-path: /provider
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/spcloud
      username: root
      password: booszy
  application:
    name: springcloud-provider
  profiles:
    active: dev
logging:
  level:
    root: info
    org.hibernate : info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.yasaka.stock : debug
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://root:booszy@localhost:8761/eureka
  instance:
#    home-page-url-path: /provider
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}